config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-scheduler/web'
Rails.application.routes.draw do
  # get 'receipt_pdfs/index', to: 'receipt_pdfs#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_out', to: 'users/sessions#destroy'
    get 'users/edit_profile', to: 'users/registrations#edit_profile'
    get 'users/edit_password', to: 'users/registrations#edit_password'
    put 'users/update_profile', to: 'users/registrations#update_profile'
    put 'users/update_password', to: 'users/registrations#update_password'
    get 'users/completed', to: 'users/registrations#completed'
  end

  root 'homes#landing'
  get 'home', to: 'homes#index', as: 'home'
  get 'faq', to: 'homes#faq', as: 'faq'
  get 'terms_of_service', to: 'homes#terms_of_service', as: 'terms_of_service'
  get 'privacy_policy', to: 'homes#privacy_policy', as: 'privacy_policy'
  get 'contact', to: 'homes#contact', as: 'contact'
  get 'users/csv_template', to: 'users#csv_template', as: 'csv_template'
  # get 'groups/:group_id/users/share', to: 'users#share', as: 'share'
  resources :groups, only: %i[new create edit update] do
    member do
      # get :deposit
      # get :statistics
      get :change
      get :inheritable_search
      post :inherit
      get :assignable_search
      post :assign
      get :resign
    end
    resources :users, only: %i[index new] do
      collection do
        post :batch
        get  :share
      end
    end
    resources :events do
      member do
        get :details
      end
    end
    resources :group_users, only: :destroy do
      collection do
        post :invite
      end
    end
    # resources :orders, only: %i[index]
  end

  resource :users, only: [] do
    resources :transactions, only: %i[edit update], controller: 'users/transactions', param: :url_token
  end
  resources :users, only: [] do
    collection do
      get :join
      get :leave
      get :withdraw
    end
    resources :transactions, only: %i[index]
    resources :transactions, only: %i[create], controller: 'users/transactions', param: :url_token do
      collection do
        get :lend
        get :borrow
      end
    end
    resources :events, only: [] do
      collection do
        get :list
      end
    end
  end

  resources :events, only: [] do
    resources :transactions, only: %i[edit update], controller: 'events/transactions', param: :url_token
    resources :fees, only: %i[new create update] do
      collection do
        post :batch
      end
    end
    resources :answers, only: %i[create edit update]
  end

  resources :transactions, only: [], param: :url_token do
    member do
      get :receipt, to: 'receipt_pdfs#show'
      patch :change
    end
  end

  resources :group_users, only: :destroy do
    collection do
      post :join
      delete :leave
    end
  end

  resources :answers, only: [] do
    member do
      patch :change
    end
  end

  # resources :questionnaires, only: %i[index create show] do
  #   resources :responses, only: %i[create update]
  # end

  # resources :orders, only: [] do
  #   collection do
  #     get 'step1'
  #     get 'step2'
  #   end
  # end
  # post 'orders/submit', to: 'orders#submit'
  # post 'orders/paypal/create_payment', to: 'orders#paypal_create_payment', as: :paypal_create_payment
  # post 'orders/paypal/execute_payment', to: 'orders#paypal_execute_payment', as: :paypal_execute_payment
  # post 'orders/paypal/create_subscription', to: 'orders#paypal_create_subscription', as: :paypal_create_subscription
  # post 'orders/paypal/execute_subscription', to: 'orders#paypal_execute_subscription', as: :paypal_execute_subscription

  ##################### ADMIN ################################
  namespace :admin do
    get 'homes/index'
    resources :questionnaires, only: %i[index new create edit update destroy] do
      resources :chooses, only: %i[index create destroy]
    end
    resources :choices, only: %i[index new create edit update destroy]
  end

  # Basic認証時のユーザー名とパスワードを設定する
  Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
    [user, password] == [ENV['SIDEKIQ_USER'], ENV['SIDEKIQ_PASSWORD']] # 環境変数にて設定
  end

  mount Sidekiq::Web => 'admin/sidekiq'

  # エラーページ
  get '*anything' => 'errors#routing_error'
end

app/views/shared/sidebar/_circle_page.html.erb
<li class="nav-item menu-items">
  <a class="nav-link" data-toggle="collapse" href="#page-layouts" aria-expanded="false" aria-controls="page-layouts">
    <span class="menu-icon">
      <i class="mdi mdi-account-multiple" style="color: #FFF001"></i>
    </span>
    <span class="menu-title">サークルページ</span>
    <i class="menu-arrow"></i>
  </a>
  <div class="collapse" id="page-layouts">
    <ul class="nav flex-column sub-menu">
      <li class="nav-item"> <a class="nav-link" href="#">サークルプロフィール(近日公開)</a></li>
      <%# <li class="nav-item"> <a class="nav-link" href="#">サークルカレンダー</a></li> %>
      <li class="nav-item"> <a class="nav-link" href="#">統計情報(近日公開)</a><%#= link_to '統計情報(未)', statistics_group_path(id: current_user_group.id), class: "nav-link" %></li>
      <li class="nav-item"> <a class="nav-link" href="#">サークル収支(近日公開)</a><%#= link_to 'デポジット(未)', deposit_group_path(id: current_user_group.id), class: "nav-link" %></li>
    </ul>
  </div>
</li>

app/views/shared/sidebar/_circle_setting.html.erb
<li class="nav-item menu-items">
  <a class="nav-link" data-toggle="collapse" href="#ui-advanced" aria-expanded="false" aria-controls="ui-advanced">
    <span class="menu-icon">
      <i class="mdi mdi-settings" style="color: #009B85"></i>
    </span>
    <span class="menu-title">サークル情報</span>
    <i class="menu-arrow"></i>
  </a>
  <div class="collapse" id="ui-advanced">
    <ul class="nav flex-column sub-menu">
      <li class="nav-item"> <%= link_to 'メンバー一覧', group_users_path(group_id: current_user_group.id), class: "nav-link" %></li>
      <li class="nav-item"> <%= link_to 'メンバー設定', change_group_path(id: current_user_group.id), class: "nav-link" %></li>
      <li class="nav-item"> <%= link_to 'サークル設定', edit_group_path(id: current_user_group.id), class: "nav-link" %></li>
      <%# <li class="nav-item"> <a class="nav-link" href="#">支払い情報(coming soon!)</a></li> %>
    </ul>
  </div>
</li>

app/views/shared/sidebar/_customize.html.erb
<%# <li class="nav-item menu-items">
  <a class="nav-link" href="#">
    <span class="menu-icon"> %>
      <%# if current_user_group.present? %>
        <%# <i class="mdi mdi-apps" style="color: #B7007C;"></i> %>
      <%# else %>
        <%# <i class="mdi mdi-apps" style="color: #0168B3;"></i> %>
      <%# end %>
    <%# </span>
    <span class="menu-title">カスタム(coming soon!)</span>
  </a>
</li> %>

app/views/shared/sidebar/_event.html.erb
<li class="nav-item menu-items">
  <a class="nav-link" data-toggle="collapse" href="#sidebar-layouts" aria-expanded="false" aria-controls="sidebar-layouts">
    <span class="menu-icon">
      <i class="mdi mdi-message-text-outline" style="color: #A0C238"></i>
    </span>
    <span class="menu-title">イベント</span>
    <i class="menu-arrow"></i>
  </a>
  <div class="collapse" id="sidebar-layouts">
    <ul class="nav flex-column sub-menu">
      <li class="nav-item"> <%= link_to 'イベント作成', new_group_event_path(group_id: current_user_group.id), class: "nav-link" %></li>
      <li class="nav-item"> <%= link_to 'イベント一覧', group_events_path(group_id: current_user_group.id), class: "nav-link" %></li>
    </ul>
  </div>
</li>

app/views/shared/sidebar/_faq.html.erb
<li class="nav-item menu-items">
  <%= link_to faq_path, class: "nav-link" do %>
    <span class="menu-icon">
      <% if current_user_group.present? %>
        <i class="mdi mdi-help-circle-outline" style="color: #6BE1E7;"></i>
      <% else %>
        <i class="mdi mdi-help-circle-outline" style="color: #A0C238"></i>
      <% end %>
    </span>
    <span class="menu-title">よくある質問</span>
  <% end %>
</li>

app/views/shared/sidebar/_home.html.erb
<li class="nav-item menu-items">
  <%= link_to home_path, class: "nav-link" do %>
    <span class="menu-icon">
      <i class="mdi mdi-home" style="color: #B80E3B;"></i>
    </span>
    <span class="menu-title">ホーム</span>
  <% end %>
</li>

app/views/shared/sidebar/_logout.html.erb
<li class="nav-item menu-items d-block d-sm-none">
  <%= link_to destroy_user_session_path, class: "nav-link", method: :delete do %>
    <span class="menu-icon">
      <i class="mdi mdi-logout" style="color:rgb(255, 255, 255);"></i>
    </span>
    <span class="menu-title">ログアウト</span>
  <% end %>
</li>

app/views/shared/sidebar/_my_page.html.erb
<li class="nav-item menu-items">
  <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
    <span class="menu-icon">
      <i class="mdi mdi-account" style="color: #D78114;"></i>
    </span>
    <span class="menu-title">マイページ</span>
    <i class="menu-arrow"></i>
  </a>
  <div class="collapse" id="ui-basic">
    <ul class="nav flex-column sub-menu">
      <% if current_user.definitive_registration %>
        <%# <li class="nav-item"> <a class="nav-link" href="#">お知らせ(coming soon!)</a></li>
        <li class="nav-item"> <a class="nav-link" href="#">Myカレンダー(coming soon!)</a></li> %>
        <li class="nav-item"> <%= link_to 'My収支', user_transactions_path(user_id: current_user.id), class: "nav-link" %></li>
        <li class="nav-item"> <%= link_to 'Myイベント', list_user_events_path(user_id: current_user.id), class: "nav-link" %></li>
        <li class="nav-item"> <%= link_to 'Myサークル設定', join_users_path, class: "nav-link" %></li>
      <% end %>
      <li class="nav-item"> <%= link_to 'プロフィール変更', users_edit_profile_path, class: "nav-link" %></li>
    </ul>
  </div>
</li>

app/views/shared/sidebar/_new_circle.html.erb
<li class="nav-item menu-items">
  <%= link_to new_group_path, class: "nav-link" do %>
    <span class="menu-icon">
      <i class="mdi mdi-account-card-details" style="color: #FFF001;"></i>
    </span>
    <span class="menu-title">サークル作成</span>
  <% end %>
</li>

app/views/shared/sidebar/_profile.html.erb
<li class="nav-item profile">
  <div class="profile-desc">
    <div class="profile-pic">
      <div class="profile-name">
        <h5 class="mb-0 font-weight-normal">
          <% if user_signed_in? %>
            <%= current_user.name %>さん
          <% else %>
            ゲストさん
          <% end %>
        </h5>
      </div>
    </div>
  </div>
</li>

app/views/shared/sidebar/_questionnaire.html.erb
<li class="nav-item menu-items">
  <a href="#" class="nav-link">
  <%#= link_to questionnaires_path, class: "nav-link" do %>
    <span class="menu-icon">
      <% if current_user_group.present? %>
        <i class="mdi mdi-lead-pencil" style="color: #0168b3;"></i>
      <% else %>
        <i class="mdi mdi-lead-pencil" style="color: #6BE1E7;"></i>
      <% end %>
    </span>
    <span class="menu-title">アンケート(近日公開)</span>
  <%# end %>
  </a>
</li>