config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-scheduler/web'
Rails.application.routes.draw do
  # get 'receipt_pdfs/index', to: 'receipt_pdfs#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_out', to: 'users/sessions#destroy'
    get 'users/edit_profile', to: 'users/registrations#edit_profile'
    get 'users/edit_password', to: 'users/registrations#edit_password'
    put 'users/update_profile', to: 'users/registrations#update_profile'
    put 'users/update_password', to: 'users/registrations#update_password'
    get 'users/completed', to: 'users/registrations#completed'
  end

  root 'homes#landing'
  get 'home', to: 'homes#index', as: 'home'
  get 'faq', to: 'homes#faq', as: 'faq'
  get 'terms_of_service', to: 'homes#terms_of_service', as: 'terms_of_service'
  get 'privacy_policy', to: 'homes#privacy_policy', as: 'privacy_policy'
  get 'contact', to: 'homes#contact', as: 'contact'
  get 'users/csv_template', to: 'users#csv_template', as: 'csv_template'
  # get 'groups/:group_id/users/share', to: 'users#share', as: 'share'
  resources :groups, only: %i[new create edit update] do
    member do
      # get :deposit
      # get :statistics
      get :change
      get :inheritable_search
      post :inherit
      get :assignable_search
      post :assign
      get :resign
    end
    resources :users, only: %i[index new] do
      collection do
        post :batch
        get  :share
      end
    end
    resources :events do
      member do
        get :details
      end
    end
    resources :group_users, only: :destroy do
      collection do
        post :invite
      end
    end
    # resources :orders, only: %i[index]
  end

  resource :users, only: [] do
    resources :transactions, only: %i[edit update], controller: 'users/transactions', param: :url_token
  end
  resources :users, only: [] do
    collection do
      get :join
      get :leave
      get :withdraw
    end
    resources :transactions, only: %i[index]
    resources :transactions, only: %i[create], controller: 'users/transactions', param: :url_token do
      collection do
        get :lend
        get :borrow
      end
    end
    resources :events, only: [] do
      collection do
        get :list
      end
    end
  end

  resources :events, only: [] do
    resources :transactions, only: %i[edit update], controller: 'events/transactions', param: :url_token
    resources :fees, only: %i[new create update] do
      collection do
        post :batch
      end
    end
    resources :answers, only: %i[create edit update]
  end

  resources :transactions, only: [], param: :url_token do
    member do
      get :receipt, to: 'receipt_pdfs#show'
      patch :change
    end
  end

  resources :group_users, only: :destroy do
    collection do
      post :join
      delete :leave
    end
  end

  resources :answers, only: [] do
    member do
      patch :change
    end
  end

  # resources :questionnaires, only: %i[index create show] do
  #   resources :responses, only: %i[create update]
  # end

  # resources :orders, only: [] do
  #   collection do
  #     get 'step1'
  #     get 'step2'
  #   end
  # end
  # post 'orders/submit', to: 'orders#submit'
  # post 'orders/paypal/create_payment', to: 'orders#paypal_create_payment', as: :paypal_create_payment
  # post 'orders/paypal/execute_payment', to: 'orders#paypal_execute_payment', as: :paypal_execute_payment
  # post 'orders/paypal/create_subscription', to: 'orders#paypal_create_subscription', as: :paypal_create_subscription
  # post 'orders/paypal/execute_subscription', to: 'orders#paypal_execute_subscription', as: :paypal_execute_subscription

  ##################### ADMIN ################################
  namespace :admin do
    get 'homes/index'
    resources :questionnaires, only: %i[index new create edit update destroy] do
      resources :chooses, only: %i[index create destroy]
    end
    resources :choices, only: %i[index new create edit update destroy]
  end

  # Basic認証時のユーザー名とパスワードを設定する
  Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
    [user, password] == [ENV['SIDEKIQ_USER'], ENV['SIDEKIQ_PASSWORD']] # 環境変数にて設定
  end

  mount Sidekiq::Web => 'admin/sidekiq'

  # エラーページ
  get '*anything' => 'errors#routing_error'
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  accepts_nested_attributes_for :group_users
  has_many :events, dependent: :destroy
  has_many :transactions, dependent: :destroy
  validates :name, presence: true, length: { maximum: 100 }
  # email
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true
  validates :email, format: { with: VALID_EMAIL_REGEX }, allow_blank: true # 一意である必要はない
  # group_number
  VALID_GROUP_NUMBER_REGEX = /\A(?=.*[a-zA-Z])(?=.*\d)[a-zA-Z\d]\w{6,25}\z/.freeze
  validates :group_number, presence: true
  validates :group_number, uniqueness: true,
                           format: { with: VALID_GROUP_NUMBER_REGEX },
                           length: { in: 6..25 },
                           allow_blank: true
  enum payment_status: { unpaid: 0, paid: 1, inactive: 2 }

  # インスタンスメソッド
  def set_paid
    self.payment_status = Group.payment_statuses[:paid]
  end

  def my_group?(user)
    Group.my_groups(user).include?(self)
  end

  def my_own_group?(user)
    self == Group.my_own_group(user)
  end

  # クラスメソッド
  def self.my_groups(user)
    groups = []
    GroupUser.where(user_id: user.id).each do |relationship|
      groups << Group.find(relationship.group_id)
    end
    groups
  end

  def self.my_own_group(user)
    relationship = GroupUser.find_by(user_id: user.id, role: GroupUser.roles[:executive])
    relationship.present? ? Group.find(relationship.group_id) : nil
  end

  def self.my_general_groups(user)
    Group.joins(:group_users).where(group_users: { user_id: user.id, role: GroupUser.roles[:general] })
  end
end

app/models/group/transaction.rb
# frozen_string_literal: true
# 今後実装予定
# class Group::Transaction < Transaction
# belongs_to :group
# end

app/controllers/groups/transactions_controller.rb
# frozen_string_literal: true
# 今後実装予定
# class Groups::TransactionsContrller < TransactionsController
#   before_action :authenticate_user!
#   def new
#     @group = Group.find(params[:group_id])
#     @transaction = Group::Transaction.new
#     @users = []
#     GroupUser.where(group_id: @group.id).each do |relationship|
#       user = User.find(relationship.user_id)
#       unless Group::Transaction.where(group_id: @group.id, event_id: null, debtor_id: relationship.user_id)
#         @users << user
#       end
#     end
#   end
#
#   def index
#     @group = Group.find(params[:group_id])
#     @transactions = Group::Transaction.where(group_id: @group.id)
#   end
# end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :confirm_definitive_registration
  before_action :set_group, except: %i[new create] # 一時的
  before_action :executives_cannot_access, only: %i[new create] # 一時的
  before_action :cannot_access_to_other_groups, only: %i[edit update change inheritable_search inherit assignable_search assign resign deposit statistics]
  before_action :only_executives_can_access, only: %i[edit update change inheritable_search inherit assignable_search assign resign deposit statistics]
  before_action :cannot_resign, only: :resign

  # def show
  #   events = Event.my_groups_events(current_user).order(start_date: :desc)
  #   @events = Kaminari.paginate_array(events).page(params[:page]).per(5)
  # end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      GroupUser.create!(
        group_id: @group.id,
        user_id: current_user.id,
        role: GroupUser.roles[:executive]
      )
      # SuccessSlackNotification.new_group_notify
      flash_and_redirect(key: :success, message: "おめでとうございます！あなたは#{@group.name}の幹事となりました！", redirect_url: home_url)
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @group.update(group_params)
      flash[:success] = 'サークルの設定を変更しました'
      redirect_to edit_group_url(id: @group.id)
    else
      render 'edit'
    end
  end

  def change
    @executives = User.executives(@group)
    user_ids = []
    GroupUser.where(group_id: @group.id, role: GroupUser.roles[:general]).each do |relationship|
      user_ids << User.find(relationship.user_id).id
    end
  end

  def inheritable_search
    incremental_search('inheritable_members')
  end

  def inherit
    @executives = User.executives(@group)
    return flash_and_render(key: :danger, message: '引継ぎたい人を選択してください。', action: 'change') if params[:new_executive].blank?

    user = new_executive
    return flash_and_render(key: :danger, message: '選択した人はすでに他のグループの幹事です。本人にご確認ください。', action: 'change') if user.blank?

    if GroupUser.inherit(group: @group, current_user: current_user, new_executive: user)
      NotificationMailer.inherit(group: @group, user: user, current_user: current_user).deliver_later
      flash_and_redirect(key: :success, message: "#{user.name}さんへ幹事を引継ぎました。", redirect_url: home_url)
    else
      ErrorSlackNotification.general_error_notify(title: '引継ぎ失敗', message: "グループID: #{@group&.id}, 引き継がれるユーザーID: #{user&.id}, 現在のユーザーID: #{current_user&.id}の引継ぎ失敗")
      flash_and_render(key: :danger, message: '引継ぎできませんでした。しばらくしてからもう一度やり直してください。', action: 'change')
    end
  end

  def assignable_search
    incremental_search('assignable_members')
  end

  def assign
    @executives = User.executives(@group)
    return flash_and_render(key: :danger, message: '任命したい人を選択してください。', action: 'change') if params[:new_executive].blank?

    user = new_executive
    return flash_and_render(key: :danger, message: '選択した人はすでに他のグループの幹事です。本人にご確認ください。', action: 'change') if user.blank?

    general_relationship = GroupUser.general_relationship(group: @group, user: user)
    if general_relationship.update(role: GroupUser.roles[:executive])
      NotificationMailer.assign(group: @group, user: user, current_user: current_user).deliver_later
      flash_and_redirect(key: :success, message: "#{user.name}さんを幹事に任命しました。", redirect_url: change_group_url(@group))
    else
      ErrorSlackNotification.general_error_notify(title: '任命失敗', message: "グループID: #{@group&.id}, 任命されるユーザーID: #{user&.id}, 現在のユーザーID: #{current_user&.id}の任命失敗")
      flash_and_render(key: :danger, message: '任命できませんでした。しばらくしてからもう一度やり直してください。', action: 'change')
    end
  end

  def resign
    executive_relationship = GroupUser.executive_relationship(group: @group, user: current_user)
    if executive_relationship.update_attribute(:role, GroupUser.roles[:general])
      flash_and_redirect(key: :success, message: '辞退しました。', redirect_url: home_url)
    else
      @executives = User.executives(@group)
      ErrorSlackNotification.general_error_notify(title: '辞退失敗', message: "グループID: #{@group&.id}, 辞退するユーザーID: #{current_user&.id}の辞退失敗")
      flash_and_render(key: :danger, message: '辞退できませんでした。しばらくしてからもう一度やり直してください。', action: 'change')
    end
  end

  def deposit; end

  def statistics; end

  private

    def set_group
      @group = Group.find(params[:id])
    end

    def group_params
      params.require(:group).permit(:name, :email, :group_number)
    end

    def new_executive
      user_id = params[:new_executive].to_i
      if GroupUser.where(user_id: user_id, role: GroupUser.roles[:executive]).present?
        nil
      else
        User.find(user_id)
      end
    end

    def incremental_search(partial)
      keyword = params[:keyword]
      user_ids = []
      GroupUser.where(group_id: @group.id, role: GroupUser.roles[:general]).each do |relationship|
        user_ids << User.find(relationship.user_id).id
      end
      members = User.where(id: user_ids)
      @members = members.where('name LIKE :keyword OR furigana LIKE :keyword ', keyword: "%#{keyword.tr('ぁ-ん', 'ァ-ン')}%").order(furigana: :asc)
      respond_to do |format|
        format.json { render partial, json: @members }
      end
    end

    def cannot_resign
      flash_and_redirect(key: :danger, message: '幹事が一人しかいないため辞退できません', redirect_url: home_url) if User.executives(@group).count == 1
    end

    # 幹事のみアクセス可能
    def only_executives_can_access
      return if current_user_group == Group.find(params[:id])

      # flash[:danger] = '幹事しかアクセスできません'
      raise Forbidden
    end

    def executives_cannot_access
      flash_and_redirect(key: :danger, message: 'すでにグループの幹事である人は新しくグループを作成することができません', redirect_url: home_url) if current_user_group
    end
end

app/helpers/groups_helper.rb
# frozen_string_literal: true

module GroupsHelper
end

app/views/groups/_assignable_members.html.erb
<div id='assignable-result'>
  <%= f.select :new_executive, {}, include_blank: '選択してください' %>
</div>

app/views/groups/_inheritable_members.html.erb
<ul id='inheritable-result'>
  <%= f.select :new_executive, {}, include_blank: '選択してください' %>
  <%# ユーザー名の表示 %>
</ul>

app/views/groups/change.html.erb
<% provide(:title, "メンバー設定") %>
<div class="sidebar-fixed container-scroller" style="background-color: rgb(44, 44, 44);">
  <nav class="sidebar sidebar-offcanvas" id="sidebar" >
    <%= render 'shared/logo'%>
    <ul class="nav">
      <%= render 'shared/sidebar/profile' %>
      <%= render 'shared/sidebar/home' %>
      <%= render 'shared/sidebar/my_page' %>
      <% if current_user_group.present? %>
        <%= render 'shared/sidebar/circle_page' %>
        <%= render 'shared/sidebar/event' %>
        <li class="nav-item menu-items active">
          <a class="nav-link" data-toggle="collapse" href="#ui-advanced" aria-expanded="false" aria-controls="ui-advanced">
            <span class="menu-icon">
              <i class="mdi mdi-settings" style="color: #009B85"></i>
            </span>
            <span class="menu-title">サークル情報</span>
            <i class="menu-arrow"></i>
          </a>
          <div class="collapse show" id="ui-advanced">
            <ul class="nav flex-column sub-menu">
              <li class="nav-item"> <%= link_to 'メンバー一覧', group_users_path(group_id: current_user_group.id), class: "nav-link" %></li>
              <li class="nav-item"> <%= link_to 'メンバー設定', change_group_path(id: current_user_group.id), class: "nav-link active" %></li>
              <li class="nav-item"> <%= link_to 'サークル設定', edit_group_path(id: current_user_group.id), class: "nav-link" %></li>
              <%# <li class="nav-item"> <a class="nav-link" href="#">支払い情報(未)</a></li> %>
            </ul>
          </div>
        </li>
      <% else %>
        <%= render 'shared/sidebar/new_circle' %>
      <% end %>
      <%= render 'shared/sidebar/faq' %>
      <%= render 'shared/sidebar/questionnaire' %>
      <%= render 'shared/sidebar/customize' %>
      <%= render 'shared/sidebar/logout' %>
    </ul>
  </nav>
  <div class="container-fluid page-body-wrapper">
    <!-- partial:partials/_navbar.html -->
    <%= render 'shared/topbar' %>
    <!-- partial -->
    <div class="main-panel">
      <div class="content-wrapper">
        <div class="page-header">
          <h3 class="page-title"> メンバー設定 </h3>
        </div>
        <%= render 'shared/flash' %>
        <div class="row">
          <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
              <div class="card-body" style="background-color: rgb(255, 255, 255); color: #000;">
                <ul class="nav nav-tabs" role="tablist">
                  <li class="nav-item">
                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home-1" role="tab" aria-controls="home" aria-selected="true">メンバー追加</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile-1" role="tab" aria-controls="profile" aria-selected="false">引継ぎ</a>
                  </li>

                  <li class="nav-item">
                    <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact-1" role="tab" aria-controls="contact" aria-selected="false">任命</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" id="contact2-tab" data-toggle="tab" href="#contact-2" role="tab" aria-controls="contact2" aria-selected="false">辞退</a>
                  </li>
                </ul>

                <div class="tab-content">
                  <div class="tab-pane fade show active" id="home-1" role="tabpanel" aria-labelledby="home-tab">
                    <section>
                      <div class="form-group">
                        <%= form_with url: invite_group_group_users_path(group_id: @group), local: true do |f| %>
                        <h4 style="display: block; font">①メンバー招待</h4>
                          <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: '招待先アドレス', class: "form-control col-md-10",
                                                    :'aria-describedby' => "emailHelp", style: "color: white; display:inline-block ;" %>
                          <%= button_tag type: "submit", class: "btn btn-danger btn-icon-text", data: { disable_with: '処理中' } do %>
                            <i class="mdi mdi-email" style="display: inline-block;"></i> 招待
                          <% end %>
                          <small id="emailHelp" class="form-text text-muted">登録したいアドレスに招待メールを送ります。</small>
                        <% end %>
                      </div>
                      <div class="form-group">
                        <%= form_with url: batch_group_users_path(group_id: @group.id), local: true, multipart: true do %>
                          <h4>②一括登録</h4>
                          <%= password_field_tag :password, nil, placeholder: "登録用初期パスワード", class: "form-control", style: "color: white;" %>
                          <%= file_field_tag :file, style: "margin-top: 10px;" %><br>
                          <%= link_to csv_template_path(format: :csv), class: "btn btn-success btn-icon-text", style: "margin-top: 10px;" do %>
                            <i class="mdi mdi-debug-step-into"></i> CSVテンプレートダウンロード
                          <% end %>
                          <%# <button type="button" class="btn btn-success btn-icon-text">
                            <i class="mdi mdi-debug-step-into"></i> csvダウンロード
                          </button> %>
                          <%= button_tag type: "submit", class: "btn btn-danger btn-icon-text", style: "margin-top: 10px;", data: { disable_with: '処理中' } do %>
                            <i class="mdi mdi-email"></i> 登録
                          <% end %>
                          <small id="emailHelp" class="form-text text-muted">csvファイルに必要事項を記入し提出してください。</small>
                        <% end %>
                      </div>
                      <div class="form-group">
                        <h4 class="card-title" style="margin-top: 25px; margin-bottom: 5px;">③ユーザー登録URLをメンバーに共有</h4>
                        <div class="row">
                          <textarea id="copyTarget" class="card card-inverse-primary col-md-9" rows="1" readonly style="overflow: hidden;">
                            <%= url_with_params(new_user_registration_url, params = { original_group_id: @group.group_number }) %>
                          </textarea>
                          <div class="col-md-3">
                            <button type="button" class="btn btn-inverse-primary btn-clipboard" onclick="copyToClipboard()">コピー</button>
                          </div>
                        </div>
                        <small class="form-text text-muted">このURLからユーザー登録を行うとこのサークルに参加することができます。</small>
                      </div>
                    </section>
                  </div>
                  <%= render 'groups/inheritance', { group: @group } %>
                  <%= render 'groups/assignment', { group: @group, executives: @executives } %>
                  <div class="tab-pane fade" id="contact-2" role="tabpanel" aria-labelledby="contact2-tab">
                    <h3>辞退</h3>
                    <section>
                      <% if @executives.count == 1 %>
                        <p>幹事が一人しかいないため辞退できません</p>
                      <% else %>
                        <button class="btn btn-outline-danger col-md-12" onclick="showSwal('warning-message-and-cancel')">辞退する</button>
                      <% end %>
                    </section>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
      <!-- content-wrapper ends -->
      <!-- partial:partials/_footer.html -->
      <%= render 'shared/footer' %>
      <!-- partial -->
    </div>
    <!-- main-panel ends -->
  </div>
  <!-- page-body-wrapper ends -->
</div>
<script>
  let inheritableSearch = $('#inheritable-search');
  let assignableSearch = $('#assignable-search');
  let groupId = inheritableSearch.data('group-id');
  let url1 = `/groups/${groupId}/inheritable_search`
  let url2 = `/groups/${groupId}/assignable_search`
  inheritableSearch.on('keyup', function(e){
    e.preventDefault(); // キャンセル可能なイベントをキャンセル
    let input = inheritableSearch.val(); // 前後の空白を取り除いて代入
    $.ajax({
      url: url1,
      type: 'GET',
      data: { keyword: input },
      // processData: false,
      contentType: false,
      dataType: 'json'
    })
    .done(function(data){
      let result = $('#inheritable-result');
      result.find('option').remove();
      result.find('li').remove();
      if (input.length !== 0){
        $(data).each(function(i, user){
          result.find('select').append(`<option value='${user.id}'>` + user.name + '</option>')
          result.append('<li>' + user.name + '</li>') // <li>ユーザーの名前</li>を追加
        });
        if (result.find('li').length === 0) {
          result.find('select').append(`<option value>` + '選択してください' + '</option>')
          result.append('<li>' + '一致するメンバーが見つかりません' + '</li>')
        }
      } else {
        result.find('select').append(`<option value>` + '選択してください' + '</option>')
      }
    })

    .fail(function() {
      alert('検索に失敗しました');
    });
  });

  assignableSearch.on('keyup', function(e){
    e.preventDefault(); // キャンセル可能なイベントをキャンセル
    let input = assignableSearch.val(); // 前後の空白を取り除いて代入
    $.ajax({
      url: url2,
      type: 'GET',
      data: { keyword: input },
      // processData: false,
      contentType: false,
      dataType: 'json'
    })
    .done(function(data){
      let result = $('#assignable-result');
      result.find('option').remove();
      result.find('li').remove();
      if (input.length !== 0){
        $(data).each(function(i, user){
          result.find('select').append(`<option value='${user.id}'>` + user.name + '</option>')
          result.append('<li>' + user.name + '</li>') // <li>ユーザーの名前</li>を追加
        });
        if (result.find('li').length === 0) {
          result.find('select').append(`<option value>` + '選択してください' + '</option>')
          result.append('<li>' + '一致するメンバーが見つかりません' + '</li>')
        }
      } else {
        result.find('select').append(`<option value>` + '選択してください' + '</option>')
      }
    })

    .fail(function() {
      alert('検索に失敗しました');
    });
  });

  (function($) {
    showSwal = function(type) {
      'use strict';
      let options = {
        title: '本当に辞退しますか?',
        text: "あなたの幹事情報が失われます！",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3f51b5',
        cancelButtonColor: '#ff4081',
        confirmButtonText: 'Great ',
        buttons: {
          cancel: {
            text: "Cancel",
            value: null,
            visible: true,
            className: "btn btn-danger",
            closeModal: true,
          },
          confirm: {
            text: "OK",
            value: true,
            visible: true,
            className: "btn btn-primary",
            closeModal: true
          }
        }
      };
      swal(options).then(function(val) {
        let url = `/groups/${groupId}/resign`
        if (val) {
          // Okボタンが押された時の処理
          window.location.href = url;
        } else {
          // キャンセルボタンを押した時の処理
          swal({
            text: "キャンセルされました",
            icon: "warning",
            buttons: false,
            timer: 1000 // 2.5秒後に自動的に閉じる
          });
        }
      });
    }
  })(jQuery);
</script>
<script>
  function copyToClipboard() {
    // コピー対象をJavaScript上で変数として定義する
    let copyTarget = $('#copyTarget')

    // コピー対象のテキストを選択する
    copyTarget.select();

    // 選択しているテキストをクリップボードにコピーする
    document.execCommand('copy');

    // コピーをお知らせする
    alert("コピーしました");
  }
</script>

app/views/groups/new.html.erb
<% provide(:title, "サークル作成") %>
<div class="sidebar-fixed container-scroller" style="background-color: rgb(44, 44, 44);">
  <nav class="sidebar sidebar-offcanvas" id="sidebar" >
    <%= render 'shared/logo'%>
    <ul class="nav">
      <%= render 'shared/sidebar/profile' %>
      <%= render 'shared/sidebar/home' %>
      <%= render 'shared/sidebar/my_page' %>
      <% if current_user_group.present? %>
        <%= render 'shared/sidebar/circle_page' %>
        <%= render 'shared/sidebar/event' %>
        <%= render 'shared/sidebar/circle_setting' %>
      <% else %>
        <li class="nav-item menu-items active">
          <%= link_to new_group_path, class: "nav-link" do %>
            <span class="menu-icon">
              <i class="  mdi mdi-account-card-details" style="color: #FFF001"></i>
            </span>
            <span class="menu-title">サークル作成</span>
          <% end %>
        </li>
      <% end %>
      <%= render 'shared/sidebar/faq' %>
      <%= render 'shared/sidebar/customize' %>
      <%= render 'shared/sidebar/questionnaire' %>
      <%= render 'shared/sidebar/logout' %>
    </ul>
  </nav>
  <div class="container-fluid page-body-wrapper">
    <!-- partial:partials/_navbar.html -->
    <%= render 'shared/topbar' %>
    <!-- partial -->
    <%= render 'shared/flash' %>
    <div class="main-panel">
      <div class="content-wrapper">
        <div class="page-header">
          <h3 class="page-title" style="color: black;"> サークル作成 </h3>
        </div>
        <div class="row">
          <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
              <div class="card-body" style="color: black;">
                <h4 class="card-title">サークル作成</h4>
                <p class="card-description">あなたのサークルを作成できます。</p>
                <ul class="nav nav-tabs" role="tablist">
                  <li class="nav-item" style="width: 100%;">
                    <div class="nav-link active">サークル情報入力</div>
                  </li>
                </ul>
                <%= form_with model: @group, url: groups_path, local: true do |f| %>
                  <div class="tab-content">
                    <div class="tab-pane fade show active">
                      <h4>サークル情報</h4>
                      <%= render 'shared/error_messages', model: f.object %>
                      <%= f.hidden_field :email, value: current_user.email %>
                      <div class="form-group" style="margin-bottom: 80px;">
                        <%= f.label :name, "グループ名", style: "margin-top: 20px;" %>
                        <%= f.text_field :name, class: "form-control", placeholder: "サークル名を入力してください", style: "color: white;" %>
                      </div>
                      <div class="form-group">
                        <%= f.label :group_number, "サークルID" %>
                        <%= f.text_field :group_number, class: "form-control", placeholder: "サークル固有のIDを入力してください", style: "color: white;" %>
                        <small class="form-text text-muted">サークルIDは文字数は6~25字、英数字(アルファベットと数字は必須)とアンダーバー(_)のみ使用できます。</small>
                      </div>
                    </div>
                    <%= f.submit "作成！", class: "btn btn-primary btn-fw offset-md-10", data: { disable_with: '処理中' } %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
      <%= render 'shared/footer' %>
    </div>
    <!-- main-panel ends -->
  </div>
  <!-- page-body-wrapper ends -->
</div>
<style>
  .field_with_errors {
    display: contents;
    /* input {
        @extend .is-invalid;
      } */
    }
</style>