config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-scheduler/web'
Rails.application.routes.draw do
  # get 'receipt_pdfs/index', to: 'receipt_pdfs#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_out', to: 'users/sessions#destroy'
    get 'users/edit_profile', to: 'users/registrations#edit_profile'
    get 'users/edit_password', to: 'users/registrations#edit_password'
    put 'users/update_profile', to: 'users/registrations#update_profile'
    put 'users/update_password', to: 'users/registrations#update_password'
    get 'users/completed', to: 'users/registrations#completed'
  end

  root 'homes#landing'
  get 'home', to: 'homes#index', as: 'home'
  get 'faq', to: 'homes#faq', as: 'faq'
  get 'terms_of_service', to: 'homes#terms_of_service', as: 'terms_of_service'
  get 'privacy_policy', to: 'homes#privacy_policy', as: 'privacy_policy'
  get 'contact', to: 'homes#contact', as: 'contact'
  get 'users/csv_template', to: 'users#csv_template', as: 'csv_template'
  # get 'groups/:group_id/users/share', to: 'users#share', as: 'share'
  resources :groups, only: %i[new create edit update] do
    member do
      # get :deposit
      # get :statistics
      get :change
      get :inheritable_search
      post :inherit
      get :assignable_search
      post :assign
      get :resign
    end
    resources :users, only: %i[index new] do
      collection do
        post :batch
        get  :share
      end
    end
    resources :events do
      member do
        get :details
      end
    end
    resources :group_users, only: :destroy do
      collection do
        post :invite
      end
    end
    # resources :orders, only: %i[index]
  end

  resource :users, only: [] do
    resources :transactions, only: %i[edit update], controller: 'users/transactions', param: :url_token
  end
  resources :users, only: [] do
    collection do
      get :join
      get :leave
      get :withdraw
    end
    resources :transactions, only: %i[index]
    resources :transactions, only: %i[create], controller: 'users/transactions', param: :url_token do
      collection do
        get :lend
        get :borrow
      end
    end
    resources :events, only: [] do
      collection do
        get :list
      end
    end
  end

  resources :events, only: [] do
    resources :transactions, only: %i[edit update], controller: 'events/transactions', param: :url_token
    resources :fees, only: %i[new create update] do
      collection do
        post :batch
      end
    end
    resources :answers, only: %i[create edit update]
  end

  resources :transactions, only: [], param: :url_token do
    member do
      get :receipt, to: 'receipt_pdfs#show'
      patch :change
    end
  end

  resources :group_users, only: :destroy do
    collection do
      post :join
      delete :leave
    end
  end

  resources :answers, only: [] do
    member do
      patch :change
    end
  end

  # resources :questionnaires, only: %i[index create show] do
  #   resources :responses, only: %i[create update]
  # end

  # resources :orders, only: [] do
  #   collection do
  #     get 'step1'
  #     get 'step2'
  #   end
  # end
  # post 'orders/submit', to: 'orders#submit'
  # post 'orders/paypal/create_payment', to: 'orders#paypal_create_payment', as: :paypal_create_payment
  # post 'orders/paypal/execute_payment', to: 'orders#paypal_execute_payment', as: :paypal_execute_payment
  # post 'orders/paypal/create_subscription', to: 'orders#paypal_create_subscription', as: :paypal_create_subscription
  # post 'orders/paypal/execute_subscription', to: 'orders#paypal_execute_subscription', as: :paypal_execute_subscription

  ##################### ADMIN ################################
  namespace :admin do
    get 'homes/index'
    resources :questionnaires, only: %i[index new create edit update destroy] do
      resources :chooses, only: %i[index create destroy]
    end
    resources :choices, only: %i[index new create edit update destroy]
  end

  # Basic認証時のユーザー名とパスワードを設定する
  Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
    [user, password] == [ENV['SIDEKIQ_USER'], ENV['SIDEKIQ_PASSWORD']] # 環境変数にて設定
  end

  mount Sidekiq::Web => 'admin/sidekiq'

  # エラーページ
  get '*anything' => 'errors#routing_error'
end

app/views/shared/_ad.html.erb
<div class="row">
  <div class="col-12 grid-margin stretch-card">
    <div class="card corona-gradient-card">
      <div class="card-body py-0 px-0 px-sm-3">
        <div class="row align-items-center">
          <div class="col-4 col-sm-3 col-xl-2">
            <%= image_pack_tag("dashboard/Group126@2x.png", class: "gradient-corona-img img-fluid", alt: "") %>
          </div>
          <div class="col-5 col-sm-7 col-xl-8 p-0">
            <h4 class="mb-1 mb-sm-0">広告？</h4>
            <p class="mb-0 font-weight-normal d-none d-sm-block">Corona admin template now with a new facelift for enhanced legibility and aesthetics!</p>
          </div>
          <div class="col-3 col-sm-2 col-xl-2 pl-0 text-center">
            <button class="btn btn-outline-light btn-rounded get-started-btn">Get Started</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_balance_chart.html.erb
<canvas id="transaction-history" class="transaction-chart"
        data-total-payment="<%= total_payment %>"
        data-total-unpaid-debt="<%= total_overdue_debt %>"
        data-total-expected-debt="<%= total_non_overdue_debt %>"></canvas>
<% if urgent_transactions.any? %>
  <% urgent_transactions.each do |transaction| %>
    <div class="bg-gray-dark d-flex d-md-block d-xl-flex flex-row py-3 px-4 px-md-3 px-xl-4 rounded mt-3">
      <div class="text-md-center text-xl-left">
        <h6 class="mb-1">期限間近の支払い <%= l transaction.deadline %></h6>
        <p class="text-muted mb-0">
          <% if event = transaction.event %>
            <%= link_to event.name, details_group_event_path(group_id: event.group_id, id: event.id) %>
          <% else %>
            <%= transaction.creditor.name %>
          <% end %>
        </p>
      </div>
      <div class="align-self-center flex-grow text-right text-md-center text-xl-right py-md-2 py-xl-0">
        <h6 class="font-weight-bold mb-0">￥<%= transaction.debt - transaction.payment %></h6>
      </div>
    </div>
  <% end %>
<% end %>
<script>
  (function($) {
  'use strict';
  $.fn.andSelf = function() {
    return this.addBack.apply(this, arguments);
  }
  $(function() {
    if ($("#transaction-history").length) {
      var $transactionHistory = $('#transaction-history');
      var $totalPayment = $transactionHistory.data('total-payment');
      var $totalUnpaidDebt = $transactionHistory.data('total-unpaid-debt');
      var $totalExpectedDebt = $transactionHistory.data('total-expected-debt');
      var areaData = {
        labels: ["支払い済み", "支払い予定","未払い"],
        datasets: [{
            data: [$totalPayment, $totalExpectedDebt, $totalUnpaidDebt],
            backgroundColor: [
              "#00d25b","#1E90FF","#FF1F00"
            ]
          }
        ]
      };
      var areaOptions = {
        responsive: true,
        maintainAspectRatio: true,
        segmentShowStroke: false,
        cutoutPercentage: 70,
        elements: {
          arc: {
              borderWidth: 0
          }
        },
        legend: {
          display: true // labelの表示
        },
        tooltips: {
          enabled: true
        }
      }
      var transactionhistoryChartPlugins = {
        beforeDraw: function(chart) {
          var width = chart.chart.width,
              height = chart.chart.height,
              ctx = chart.chart.ctx;

          ctx.restore();
          var fontSize = 1;
          ctx.font = fontSize + "rem sans-serif";
          ctx.textAlign = 'left';
          ctx.textBaseline = "middle";
          ctx.fillStyle = "#ffffff";

          var text = "$1200",
              textX = Math.round((width - ctx.measureText(text).width) / 2),
              textY = height / 2.4;

          ctx.fillText(text, textX, textY);

          ctx.restore();
          var fontSize = 0.75;
          ctx.font = fontSize + "rem sans-serif";
          ctx.textAlign = 'left';
          ctx.textBaseline = "middle";
          ctx.fillStyle = "#6c7293";

          // var texts = "イベント収支",
          //     textsX = Math.round((width - ctx.measureText(text).width) / 2.0),
          //     textsY = height / 1.8;

          // ctx.fillText(texts, textsX, textsY);
          // ctx.save();
        }
      }
      var transactionhistoryChartCanvas = $("#transaction-history").get(0).getContext("2d");
      var transactionhistoryChart = new Chart(transactionhistoryChartCanvas, {
        type: 'doughnut',
        data: areaData,
        options: areaOptions,
        plugins: transactionhistoryChartPlugins
      });
    }
  });
})(jQuery);
</script>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="d-sm-flex justify-content-center justify-content-sm-between">
    <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2020 <a href="https://www.bootstrapdash.com/" target="_blank">Circle-tree</a>. All rights reserved.</span>
    <%# <span class="text-muted float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span> %>
  </div>
</footer>

app/views/shared/_logo.html.erb
<div class="sidebar-brand-wrapper d-none d-lg-flex align-items-center justify-content-center fixed-top">
  <%= link_to home_url, class: "sidebar-brand brand-logo" do %>
    <%= image_pack_tag("logo_G2.png", alt: "logo") %>
  <% end %>
</div>

app/views/shared/_sidebar.html.erb
<nav class="sidebar sidebar-offcanvas" id="sidebar" >
  <%= render 'shared/logo'%>
  <ul class="nav">
    <%= render 'shared/sidebar/profile' %>
    <%= render 'shared/sidebar/home' %>
    <%= render 'shared/sidebar/my_page' %>
    <% if current_user_group.present? %>
      <%= render 'shared/sidebar/circle_page' %>
      <%= render 'shared/sidebar/event' %>
      <%= render 'shared/sidebar/circle_setting' %>
    <% else %>
      <%= render 'shared/sidebar/new_circle' %>
    <% end %>
    <%= render 'shared/sidebar/faq' %>
    <%= render 'shared/sidebar/questionnaire' %>
    <%= render 'shared/sidebar/customize' %>
    <%= render 'shared/sidebar/logout' %>
  </ul>
</nav>

app/views/shared/_topbar.html.erb
<nav class="navbar p-0 fixed-top d-flex flex-row">
  <div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
    <%= link_to home_url, class: "navbar-brand brand-logo-mini" do %>
      <%= image_pack_tag("logo-mini.svg", alt: "logo") %>
    <% end %>
  </div>
  <div class="navbar-menu-wrapper flex-grow d-flex align-items-stretch">
  <%# アコーディオンを一時的に削除 %>
    <%# <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize"> %>
      <%# <span class="mdi mdi-menu"></span> %>
    <%# </button> %>
    <ul class="navbar-nav w-100">
      <li class="nav-item w-100">
        <form class="nav-link mt-2 mt-md-0 d-none d-lg-flex search">
          <input type="text" class="form-control" placeholder="検索" style="color: white;">
        </form>
      </li>
    </ul>
    <ul class="navbar-nav navbar-nav-right">
      <% if user_signed_in? %>
        <% if current_user_group %>
          <li class="nav-item dropdown d-none d-lg-block">
            <%= link_to '+ イベント新規作成', new_group_event_path(group_id: current_user_group.id), class: "nav-link btn btn-success create-new-button" %>
          </li>
        <% end %>
      <% end %>
      <%= render 'shared/user_setting' %>
    </ul>
    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
      <span class="mdi mdi-format-line-spacing"></span>
    </button>
  </div>
</nav>

app/views/shared/_user_setting.html.erb
<li class="nav-item dropdown">
  <a class="nav-link" id="profileDropdown" href="#" data-toggle="dropdown">
    <div class="navbar-profile">
    <p class="mb-0 d-none d-sm-block navbar-profile-name">設定</p>
    <i class="mdi mdi-menu-down d-none d-sm-block"></i>
    </div>
  </a>
  <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="profileDropdown">
    <h6 class="p-3 mb-0">設定</h6>
    <% if user_signed_in? %>
      <div class="dropdown-divider"></div>
      <%= link_to users_edit_profile_path, class: "dropdown-item preview-item" do %>
        <div class="preview-thumbnail">
            <div class="preview-icon bg-dark rounded-circle">
            <i class="mdi mdi-settings text-success"></i>
            </div>
        </div>
        <div class="preview-item-content">
            <p class="preview-subject mb-1">プロフィール設定</p>
        </div>
      <% end %>
      <div class="dropdown-divider"></div>

      <% unless current_user_group %>
        <%= link_to new_group_path, class: "dropdown-item preview-item" do %>
          <div class="preview-thumbnail">
              <div class="preview-icon bg-dark rounded-circle">
              <i class="mdi mdi-currency-eth text-danger"></i>
              </div>
          </div>
          <div class="preview-item-content">
              <p class="preview-subject mb-1">サークル作成</p>
          </div>
        <% end %>
      <% end %>

      <%= link_to destroy_user_session_path, class: "dropdown-item preview-item", method: :delete do %>
        <div class="preview-thumbnail">
            <div class="preview-icon bg-dark rounded-circle">
            <i class="mdi mdi-logout text-danger"></i>
            </div>
        </div>
        <div class="preview-item-content">
            <p class="preview-subject mb-1">ログアウト</p>
        </div>
      <% end %>
    <% else %>
      <%= link_to new_user_session_path, class: "dropdown-item preview-item" do %>
        <div class="preview-thumbnail">
            <div class="preview-icon bg-dark rounded-circle">
            <i class="mdi mdi-logout text-danger"></i>
            </div>
        </div>
        <div class="preview-item-content">
            <p class="preview-subject mb-1">ログイン</p>
        </div>
      <% end %>
    <% end %>
  </div>
</li>