config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-scheduler/web'
Rails.application.routes.draw do
  # get 'receipt_pdfs/index', to: 'receipt_pdfs#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_out', to: 'users/sessions#destroy'
    get 'users/edit_profile', to: 'users/registrations#edit_profile'
    get 'users/edit_password', to: 'users/registrations#edit_password'
    put 'users/update_profile', to: 'users/registrations#update_profile'
    put 'users/update_password', to: 'users/registrations#update_password'
    get 'users/completed', to: 'users/registrations#completed'
  end

  root 'homes#landing'
  get 'home', to: 'homes#index', as: 'home'
  get 'faq', to: 'homes#faq', as: 'faq'
  get 'terms_of_service', to: 'homes#terms_of_service', as: 'terms_of_service'
  get 'privacy_policy', to: 'homes#privacy_policy', as: 'privacy_policy'
  get 'contact', to: 'homes#contact', as: 'contact'
  get 'users/csv_template', to: 'users#csv_template', as: 'csv_template'
  # get 'groups/:group_id/users/share', to: 'users#share', as: 'share'
  resources :groups, only: %i[new create edit update] do
    member do
      # get :deposit
      # get :statistics
      get :change
      get :inheritable_search
      post :inherit
      get :assignable_search
      post :assign
      get :resign
    end
    resources :users, only: %i[index new] do
      collection do
        post :batch
        get  :share
      end
    end
    resources :events do
      member do
        get :details
      end
    end
    resources :group_users, only: :destroy do
      collection do
        post :invite
      end
    end
    # resources :orders, only: %i[index]
  end

  resource :users, only: [] do
    resources :transactions, only: %i[edit update], controller: 'users/transactions', param: :url_token
  end
  resources :users, only: [] do
    collection do
      get :join
      get :leave
      get :withdraw
    end
    resources :transactions, only: %i[index]
    resources :transactions, only: %i[create], controller: 'users/transactions', param: :url_token do
      collection do
        get :lend
        get :borrow
      end
    end
    resources :events, only: [] do
      collection do
        get :list
      end
    end
  end

  resources :events, only: [] do
    resources :transactions, only: %i[edit update], controller: 'events/transactions', param: :url_token
    resources :fees, only: %i[new create update] do
      collection do
        post :batch
      end
    end
    resources :answers, only: %i[create edit update]
  end

  resources :transactions, only: [], param: :url_token do
    member do
      get :receipt, to: 'receipt_pdfs#show'
      patch :change
    end
  end

  resources :group_users, only: :destroy do
    collection do
      post :join
      delete :leave
    end
  end

  resources :answers, only: [] do
    member do
      patch :change
    end
  end

  # resources :questionnaires, only: %i[index create show] do
  #   resources :responses, only: %i[create update]
  # end

  # resources :orders, only: [] do
  #   collection do
  #     get 'step1'
  #     get 'step2'
  #   end
  # end
  # post 'orders/submit', to: 'orders#submit'
  # post 'orders/paypal/create_payment', to: 'orders#paypal_create_payment', as: :paypal_create_payment
  # post 'orders/paypal/execute_payment', to: 'orders#paypal_execute_payment', as: :paypal_execute_payment
  # post 'orders/paypal/create_subscription', to: 'orders#paypal_create_subscription', as: :paypal_create_subscription
  # post 'orders/paypal/execute_subscription', to: 'orders#paypal_execute_subscription', as: :paypal_execute_subscription

  ##################### ADMIN ################################
  namespace :admin do
    get 'homes/index'
    resources :questionnaires, only: %i[index new create edit update destroy] do
      resources :chooses, only: %i[index create destroy]
    end
    resources :choices, only: %i[index new create edit update destroy]
  end

  # Basic認証時のユーザー名とパスワードを設定する
  Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
    [user, password] == [ENV['SIDEKIQ_USER'], ENV['SIDEKIQ_PASSWORD']] # 環境変数にて設定
  end

  mount Sidekiq::Web => 'admin/sidekiq'

  # エラーページ
  get '*anything' => 'errors#routing_error'
end

app/controllers/events/transactions_controller.rb
# frozen_string_literal: true

class Events::TransactionsController < TransactionsController
  before_action :authenticate_user!
  before_action :confirm_definitive_registration
  before_action :set_group_and_event
  before_action :cannot_access_to_other_groups
  before_action :only_executives_can_access

  def edit
    @transaction = Event::Transaction.find_by(url_token: params[:url_token])
    @user = @transaction.debtor
    @executives = User.executives(@group)
  end

  def update
    @transaction = Event::Transaction.find_by(url_token: params[:url_token])
    if @transaction.update(update_transaction_params)
      TransactionNotificationMailer.update_event_transaction(group: @group, transaction: @transaction, current_user: current_user).deliver_later
      flash[:success] = "#{@transaction.debtor.name}さんの支払い情報を更新しました"
      redirect_to group_event_url(group_id: @event.group_id, id: @event.id)
    else
      @user = @transaction.debtor
      @executives = User.executives(@group)
      render 'edit'
    end
  end

  private

    def update_transaction_params
      params.require(:event_transaction).permit(:deadline, :debt, :payment, :creditor_id)
    end

    def set_group_and_event
      @event = Event.find(params[:event_id])
      @group = @event.group
    end

    # 幹事のみアクセス可能
    def only_executives_can_access
      return if current_user_group == @group

      # flash[:danger] = '幹事しかアクセスできません'
      raise Forbidden
    end
end

app/controllers/groups/transactions_controller.rb
# frozen_string_literal: true
# 今後実装予定
# class Groups::TransactionsContrller < TransactionsController
#   before_action :authenticate_user!
#   def new
#     @group = Group.find(params[:group_id])
#     @transaction = Group::Transaction.new
#     @users = []
#     GroupUser.where(group_id: @group.id).each do |relationship|
#       user = User.find(relationship.user_id)
#       unless Group::Transaction.where(group_id: @group.id, event_id: null, debtor_id: relationship.user_id)
#         @users << user
#       end
#     end
#   end
#
#   def index
#     @group = Group.find(params[:group_id])
#     @transactions = Group::Transaction.where(group_id: @group.id)
#   end
# end

app/controllers/transactions_controller.rb
# frozen_string_literal: true

class TransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :confirm_definitive_registration
  before_action :other_user_cannot_access, only: %i[index]
  before_action :only_executives_can_access, only: %i[change]

  def index
    user = current_user
    @today = Time.current.midnight
    transactions = Transaction.transactions_for_attending_event_by_user(user)
    @transactions = transactions.includes(:creditor).order(deadline: :asc).page(params[:page]).per(5)
    @total_payment = transactions.sum { |transaction| transaction[:payment] }
    uncompleted_transactions = Transaction.uncompleted_transactions_by_user(transactions)
    overdue_transactions = Transaction.overdue_transactions_by_user(uncompleted_transactions: uncompleted_transactions, today: @today)
    @total_overdue_debt = overdue_transactions.sum { |transaction| transaction[:debt] } - overdue_transactions.sum { |transaction| transaction[:payment] }
    non_overdue_transactions = uncompleted_transactions - overdue_transactions
    @total_non_overdue_debt = non_overdue_transactions.sum { |transaction| transaction[:debt] } - non_overdue_transactions.sum { |transaction| transaction[:payment] }
    @urgent_transactions = Transaction.urgent_transactions_by_user(non_overdue_transactions: non_overdue_transactions, max: 2, today: @today)

    @individual_transactions = Individual::Transaction.includes(:debtor, :creditor).where('debtor_id = ? OR creditor_id = ?', user.id, user.id).order(deadline: 'ASC').page(params[:page]).per(5)
  end

  # def new
  #   @group = Group.find(params[:group_id])
  #   @event = Event.find(params[:event_id])
  #   @transaction = Transaction.new
  # end

  # def create
  #   @group = Group.find(params[:group_id])
  #   @event = Event.find(params[:event_id])
  #   @transaction = Transaction.new(transaction_params)
  #   if @transaction.save
  #     flash[:success] = 'トランザクション作成成功！'
  #     redirect_to group_event_url(group_id: @group.id, id: @event.id)
  #   else
  #     render 'new'
  #   end
  # end

  # def edit
  # end

  # def update
  # end

  def change
    url_token = params[:url_token]
    payment = params[:payment]
    if url_token && payment && transaction = Transaction.find_by(url_token: url_token)
      if transaction&.update(payment: payment)
        TransactionNotificationMailer.update_event_transaction(group: transaction.event.group, transaction: transaction, current_user: current_user).deliver_later
        render partial: 'events/show/transaction', locals: { transaction: transaction }
      else
        message = "#{current_user.name}(ID: #{current_user&.id})さんがTransaction ID: #{transaction&.id}のステータスを「完了」にできないエラー"
        ErrorSlackNotification.general_error_notify(title: 'Transactionのステータスを完了にできないエラー', message: message)
        render json: { error: '404 error' }, status: 404
      end
    else
      render json: { error: '404 error' }, status: 404
    end
  end

  # private

  # def transaction_params
  #   params.require(:transaction).permit(:debtor_id, :creditor_id, :event_id, :group_id, :deadline, :debt, :payment)
  # end

  # def transaction_params
  #  params.require(params[:type].underscore.gsub('/', '_').to_sym).permit(:debtor_id, :creditor_id, :event_id, :group_id, :deadline, :debt, :payment)
  # end
  # "Transaction::Event".underscore => "transaction/event"
  # "transaction/event".gsub('/', '_') => "transaction_event" 第1引数にマッチしたものを第2引数に置き換える
  # .to_sym => 文字列をシンボルに変換する

  # 幹事のみアクセス可能
  def only_executives_can_access
    transaction = Event::Transaction.find_by(url_token: params[:url_token])
    return if current_user_group == transaction.event.group

    # flash[:danger] = '幹事しかアクセスできません'
    raise Forbidden
  end
end

app/controllers/users/transactions_controller.rb
# frozen_string_literal: true

class Users::TransactionsController < TransactionsController
  before_action :authenticate_user!
  before_action :confirm_definitive_registration
  before_action :cannot_individual_transaction_to_myself, only: %i[lend borrow create]

  def lend
    @transaction = Individual::Transaction.new
  end

  def borrow
    @transaction = Individual::Transaction.new
  end

  def create
    @user = User.find(params[:user_id])
    @transaction = Individual::Transaction.new(user_transaction_params)
    @transaction.url_token = SecureRandom.hex(10)
    if @transaction.save
      if @transaction.lending?(user: current_user)
        TransactionNotificationMailer.new_lending_transaction(user: @user, current_user: current_user).deliver_later
      else
        TransactionNotificationMailer.new_borrowing_transaction(user: @user, current_user: current_user).deliver_later
      end
      flash_and_redirect(key: :success, message: '作成しました。', redirect_url: user_transactions_path(user_id: current_user.id))
    else
      if @transaction.lending?(user: current_user)
        render 'lend'
      else
        render 'borrow'
      end
    end
  end

  def edit
    @transaction = Individual::Transaction.find_by(url_token: params[:url_token])
    @user = if @transaction.lending?(user: current_user)
              @transaction.debtor
            else
              @transaction.creditor
            end
  end

  def update
    @transaction = Individual::Transaction.find_by(url_token: params[:url_token])
    if @transaction.update(update_user_transaction_params)
      if @transaction.lending?(user: current_user)
        TransactionNotificationMailer.update_lending_transaction(user: @transaction.debtor, current_user: current_user).deliver_later
      else
        TransactionNotificationMailer.update_borrowing_transaction(user: @transaction.creditor, current_user: current_user).deliver_later
      end
      flash_and_redirect(key: :success, message: '変更しました。', redirect_url: user_transactions_path(user_id: current_user.id))
    else
      @user = if @transaction.lending?(user: current_user)
                @transaction.debtor
              else
                @transaction.creditor
              end
      render 'edit'
    end
  end

  private

    def user_transaction_params
      params.require(:individual_transaction).permit(:deadline, :debt, :payment, :memo, :debtor_id, :creditor_id)
    end

    def update_user_transaction_params
      params.require(:individual_transaction).permit(:deadline, :debt, :payment, :memo)
    end

    def cannot_individual_transaction_to_myself
      @user = User.find(params[:user_id])
      flash_and_redirect(key: :danger, message: '自分に対する貸し借りメモは作成できません。', redirect_url: home_url) if current_user.id == @user.id
    end
end

app/helpers/transactions_helper.rb
# frozen_string_literal: true

module TransactionsHelper
end

app/views/transactions/index.html.erb
<% provide(:title, "My収支") %>
<div class="sidebar-fixed container-scroller" style="background-color: rgb(44, 44, 44);">
  <nav class="sidebar sidebar-offcanvas" id="sidebar" >
    <%= render 'shared/logo'%>
    <ul class="nav">
      <%= render 'shared/sidebar/profile' %>
      <%= render 'shared/sidebar/home' %>
      <li class="nav-item menu-items active">
        <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
          <span class="menu-icon">
            <i class="mdi mdi-account" style="color: #D78114;"></i>
          </span>
          <span class="menu-title">マイページ</span>
          <i class="menu-arrow"></i>
        </a>
        <div class="collapse show" id="ui-basic">
          <ul class="nav flex-column sub-menu show">
            <% if current_user.definitive_registration %>
              <%# <li class="nav-item"> <a class="nav-link" href="#">お知らせ(coming soon!)</a></li>
              <li class="nav-item"> <a class="nav-link" href="#">Myカレンダー(coming soon!)</a></li> %>
              <li class="nav-item"> <%= link_to 'My収支', user_transactions_path(user_id: current_user.id), class: "nav-link active" %></li>
              <li class="nav-item"> <%= link_to 'Myイベント', list_user_events_path(user_id: current_user.id), class: "nav-link" %></li>
              <li class="nav-item"> <%= link_to 'Myサークル設定', join_users_path, class: "nav-link" %></li>
            <% end %>
            <li class="nav-item"> <%= link_to 'プロフィール変更', users_edit_profile_path, class: "nav-link" %></li>
          </ul>
        </div>
      </li>
      <% if current_user_group.present? %>
        <%= render 'shared/sidebar/circle_page' %>
        <%= render 'shared/sidebar/event' %>
        <%= render 'shared/sidebar/circle_setting' %>
      <% else %>
        <%= render 'shared/sidebar/new_circle' %>
      <% end %>
      <%= render 'shared/sidebar/faq' %>
      <%= render 'shared/sidebar/questionnaire' %>
      <%= render 'shared/sidebar/customize' %>
      <%= render 'shared/sidebar/logout' %>
    </ul>
  </nav>
  <div class="container-fluid page-body-wrapper">
    <!-- partial:partials/_navbar.html -->
    <%= render 'shared/topbar' %>
    <!-- partial -->
    <div class="main-panel">
      <div class="content-wrapper">
        <%#= render 'shared/ad' %>
        <div class="page-header">
          <h3 class="page-title"> My収支 </h3>
        </div>
        <%= render 'shared/flash' %>

        <div class="row">
          <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
              <div class="card-body" style="color: white;">
                <h4 class="card-title">イベント収支情報</h4>
                <% values = { total_payment: @total_payment, total_overdue_debt: @total_overdue_debt,
                              total_non_overdue_debt: @total_non_overdue_debt, urgent_transactions: @urgent_transactions } %>
                <%= render 'shared/balance_chart', values %>
              </div>
            </div>
          </div>
          <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
              <div class="card-body" style="color: black;">
                <h4 class="card-title">イベント支払い履歴</h4>
                <div class="row">
                  <div class="col-12">
                    <div class="table-responsive">
                      <table id="order-listing" class="table">
                        <thead>
                          <tr>
                            <th>イベント名</th>
                            <th>支払い期限</th>
                            <th>金額</th>
                            <th>支払った金額</th>
                            <th>支払い相手</th>
                            <th>支払い状況</th>
                            <th>領収書発行</th>
                          </tr>
                        </thead>
                        <tbody>
                          <% @transactions.each do |transaction| %>
                            <% deadline = transaction.deadline %>
                            <% debt = transaction.debt %>
                            <% payment = transaction.payment %>
                            <% event = Event.find(transaction.event_id) %>
                            <tr>
                              <td>
                                <%= link_to event.name.truncate(20), details_group_event_path(group_id: event.group_id, id: event.id), style: 'color: black;' %>
                              </td>
                              <td><%= l deadline, format: :short %></td>
                              <td><%= number_to_currency(transaction.debt) %></td>
                              <td><%= number_to_currency(transaction.payment) %></td>
                              <td><%= transaction.creditor.name %></td>
                              <% if debt == payment %>
                                <td>
                                  <label class="badge badge-success">完了</label>
                                </td>
                                <td>
                                  <%= link_to "発行", receipt_transaction_path(url_token: transaction.url_token, format: "pdf"), class: "btn btn-outline-primary" %>
                                </td>
                              <% elsif debt > payment %>
                                <td>
                                  <% if deadline > @today %>
                                    <label class="badge badge-primary">予定</label>
                                  <% else %>
                                    <label class="badge badge-danger">未払い</label>
                                  <% end %>
                                </td>
                                <td></td>
                              <% else %>
                                <td>
                                  <label class="badge badge-info">過払い</label>
                                </td>
                                <td></td>
                              <% end %>
                            </tr>
                          <% end %>
                        </tbody>
                      </table>
                      <%= paginate @transactions %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
              <div class="card-body" style="color: black;">
                <h4 class="card-title">貸し借りメモ</h4>
                <div class="row">
                  <div class="col-12">
                    <div class="table-responsive">
                      <table id="order-listing" class="table">
                        <thead>
                          <tr>
                            <th>貸し借り</th>
                            <th>支払い相手</th>
                            <th>金額</th>
                            <th>支払った金額</th>
                            <th>期限</th>
                            <th>メモ</th>
                            <th>支払い状況</th>
                            <th>変更</th>
                          </tr>
                        </thead>
                        <tbody>
                          <% @individual_transactions.each do |transaction| %>
                            <% deadline = transaction.deadline %>
                            <% debt = transaction.debt %>
                            <% payment = transaction.payment %>
                            <% url_token = transaction.url_token %>
                            <tr>
                              <td>
                                <% is_lending = transaction.lending?(user: current_user) %>
                                <% if is_lending %>
                                  <label class="btn btn-outline-primary">貸した</label>
                                <% else %>
                                  <label class="btn btn-outline-danger">借りた</label>
                                <% end %>
                              </td>
                              <td>
                                <% if is_lending %>
                                  <%= transaction.debtor.name %>
                                <% else %>
                                  <%= transaction.creditor.name %>
                                <% end %>
                              </td>
                              <td><%= number_to_currency(transaction.debt) %></td>
                              <td><%= number_to_currency(transaction.payment) %></td>
                              <td><%= l deadline, format: :short %></td>
                              <td><%= transaction.memo %></td>
                              <% if debt == payment %>
                                <td>
                                  <label class="badge badge-success">完了</label>
                                </td>
                              <% elsif debt > payment %>
                                <td>
                                  <% if deadline > @today %>
                                    <label class="badge badge-primary">予定</label>
                                  <% else %>
                                    <label class="badge badge-danger">未完了</label>
                                  <% end %>
                                </td>
                              <% else %>
                                <td>
                                  <label class="badge badge-info">過払い</label>
                                </td>
                              <% end %>
                              <td><%= link_to '変更する', edit_users_transaction_path(url_token: url_token), class: "btn btn-outline-primary" %></td>
                            </tr>
                          <% end %>
                        </tbody>
                      </table>
                      <%= paginate @individual_transactions %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
      <!-- partial:partials/_footer.html -->
      <%= render 'shared/footer' %>
      <!-- partial -->
    </div>
    <!-- main-panel ends -->
  </div>
  <!-- page-body-wrapper ends -->
</div>